export const schedule = [{
        id: 0,
        timeslot: "8-9h",
        available: true,
        date: "17/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 1,
        timeslot: "9-10h",
        available: true,
        date: "18/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 2,
        timeslot: "10-11h",
        available: true,
        date: "17/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 3,
        timeslot: "12-13h",
        available: true,
        date: "18/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 4,
        timeslot: "13-14h",
        available: true,
        date: "17/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 5,
        timeslot: "14-15h",
        available: true,
        date: "17/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 6,
        timeslot: "15-16h",
        available: true,
        date: "18/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 7,
        timeslot: "16-17h",
        available: true,
        date: "17/5/2022",
        name: "",
        email: "",
        subject: "",
    },
    {
        id: 8,
        timeslot: "17-18h",
        available: true,
        date: "19/5/2022",
        name: "",
        email: "",
        subject: "",
    },
];